service: mailer

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: post
          cors: true